StuWare/Controllers/GradeController.cs
using Microsoft.AspNetCore.Mvc;
using StuWare.Data.Repository;
using StuWare.Helpers;
using StuWare.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StuWare.Controllers
{
    public class GradeController : StuwareController
    {

        private IStudentLessonGradeRepository _studentLessonGradeRepository;
        private static int selectedStudentLessonId;

        public GradeController(IStudentLessonGradeRepository studentLessonGradeRepository)
        {
            _studentLessonGradeRepository = studentLessonGradeRepository;
        }

        public IActionResult Index(int id)
        {
            selectedStudentLessonId = id;
            return View(_studentLessonGradeRepository.studentLessongrades.Where(x => x.StudentLessonID.Equals(id)));
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(StudentLessonGrade entity)
        {
            entity.StudentLessonID = selectedStudentLessonId;

            if (ModelState.IsValid)
            {
                _studentLessonGradeRepository.CreateStudentLessonGrade(entity);
                return RedirectToAction("Index", new { id = selectedStudentLessonId });
            }
            else
            {
                return View(entity);
            }
        }

        public IActionResult Delete(int id)
        {
            _studentLessonGradeRepository.DeleteStudentLessonGrade(id);
            return RedirectToAction("Index", new { id = selectedStudentLessonId });
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            return View(_studentLessonGradeRepository.GetById(id));
        }

        [HttpPost]
        public IActionResult Details(StudentLessonGrade entity)
        {
            if (ModelState.IsValid)
            {
                entity.StudentLessonID = selectedStudentLessonId;
                _studentLessonGradeRepository.UpdateStudentLessonGrade(entity);
                return RedirectToAction("Index", new { id = selectedStudentLessonId });
            }
            else
            {
                return View(entity);
            }
        }

    }
}

StuWare/Controllers/StudentLessonController.cs
using Microsoft.AspNetCore.Mvc;
using StuWare.Data.Repository;
using StuWare.Helpers;
using StuWare.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StuWare.Controllers
{
    public class StudentLessonController : StuwareController
    {
        private IStudentLessonRepository _studentLessonRepository;
        private IStudentRepository _studentRepository;
        private ILessonRepository _lessonRepository;

        public StudentLessonController(IStudentLessonRepository studentLessonRepository,IStudentRepository studentRepository,ILessonRepository lessonRepository)
        {
            _studentLessonRepository = studentLessonRepository;
            _studentRepository = studentRepository;
            _lessonRepository = lessonRepository; 
        }

        private static int selectedStudentId = 0;

        public IActionResult Index(int id)
        {
            selectedStudentId = id;
            ViewBag.selectedStudentId = selectedStudentId;

            List<int> selectedClassList = new List<int>();
            var student = _studentRepository.GetById(selectedStudentId);
            var studentlessonsForSpecificYearList = _lessonRepository.Lessons.Where(x => x.Class.Equals(student.ClassYear));

            foreach (var item in studentlessonsForSpecificYearList.ToList())
            {
                if (_studentLessonRepository.StudentLessons.Where(x => x.StudentID.Equals(selectedStudentId) && x.LessonID.Equals(item.ID)).Count() > 0)
                    selectedClassList.Add(item.ID);

            }

            ViewBag.SelectedClassLists = selectedClassList;

            return View(studentlessonsForSpecificYearList);
        }


        public IActionResult Create(int id)
        {
            if (_studentLessonRepository.StudentLessons.Where(x => x.StudentID.Equals(selectedStudentId) && x.LessonID.Equals(id)).Count() > 0)
                throw new Exception("Duplicated");

            _studentLessonRepository.CreateStudentLesson(new StudentLesson
            {
                LessonID = id,
                StudentID = selectedStudentId
            });

            return RedirectToAction("Index", new { id = selectedStudentId });
        }

        public IActionResult Delete(int id)
        {
            int lessonId = id;
            var studentLesson = _studentLessonRepository.StudentLessons.Where(x => x.StudentID.Equals(selectedStudentId) && x.LessonID.Equals(lessonId)).FirstOrDefault();
            _studentLessonRepository.DeleteStudentLesson(studentLesson.ID);
            return RedirectToAction("Index", new { id = selectedStudentId });
        }
    }
}

StuWare/Views/StudentLesson/Index.cshtml
@model IEnumerable<Lesson>

    <h3>Ders Programı</h3>
    <br />

<table class="table">
    <thead class="table-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">DersAdı</th>
            <th scope="col">Sınıf</th>
            <th scope="col">Ders Ata</th>
            <th scope="col">Not</th>
            <th scope="col">Atanmış Dersi Kaldır</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <th scope="row">@item.ID</th>
            <td>@item.Name</td>
            <td>@item.Class</td>

            @if (!(ViewBag.SelectedClassLists as List<int>).Contains(item.ID))
            {
                <td>

                    <a asp-action="Create" asp-controller="StudentLesson" asp-route-id="@item.ID">
                        Dersi Ata
                    </a>

                </td>

                <td>
                    Bu ders atanmamıştır.
                </td>
                <td>
                   
                     

                 
                </td>

            }
            else
            {
                <td>
                    Bu ders atanmıştır.
                </td>

                <td>
                    <a asp-action="Index" asp-controller="Grade" asp-route-id="@item.StudentLessons.Where(s=>s.LessonID.Equals(item.ID) && s.StudentID.Equals(ViewBag.selectedStudentId)).FirstOrDefault().ID">
                        Not Gir
                    </a>
                </td>
                <td>
                    <a asp-action="Delete" asp-controller="StudentLesson" asp-route-id="@item.ID" onclick="return confirm('Atanmış dersi kaldırdığınızda giriş yapılan tüm notlar silinecektir. Devam etmek istediğinize emin misiniz?')">
                        Atanmış Dersi Kaldır
                    </a>
                </td>
            }


        </tr>
        }

    </tbody>
</table>