StuWare/Controllers/LessonController.cs
using Microsoft.AspNetCore.Mvc;
using StuWare.Data.Repository;
using StuWare.Helpers;
using StuWare.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StuWare.Controllers
{
    public class LessonController : StuwareController
    {
        private ILessonRepository _lessonRepository;
        private ITeacherRepository _teacherRepository;

        public LessonController(ILessonRepository lessonrepository, ITeacherRepository teacherRepository)
        {
            _lessonRepository = lessonrepository;
            _teacherRepository = teacherRepository;
        }

        public IActionResult Index()
        {
            return View(_lessonRepository.Lessons);
        }

        [HttpGet]
        public IActionResult Create()
        {

            List<Teacher> teacherList = _teacherRepository.Teachers.ToList<Teacher>();
            ViewBag.ListOfTeachers = teacherList;

            return View();
        }

        [HttpPost]
        public IActionResult Create(Lesson entity)
        {
            if (ModelState.IsValid)
            {
                _lessonRepository.CreateLesson(entity);
                return RedirectToAction("Index");
            }
            else
            {
                List<Teacher> teacherList = _teacherRepository.Teachers.ToList<Teacher>();
                ViewBag.ListOfTeachers = teacherList;
                return View(entity);
            }
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            List<Teacher> teacherList = _teacherRepository.Teachers.ToList<Teacher>();
            ViewBag.ListOfTeachers = teacherList;

            return View(_lessonRepository.GetById(id));
        }

        [HttpPost]
        public IActionResult Details(Lesson entity)
        {

            if (ModelState.IsValid)
            {
                _lessonRepository.UpdateLesson(entity);
                return RedirectToAction("Index");
            }
            else
            {
                return View(entity);
            }

        }


        public IActionResult Delete(int id)
        {
            _lessonRepository.DeleteLesson(id);
            return RedirectToAction("Index");
        }

    }
}

StuWare/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using StuWare.Data.Repository;
using StuWare.Helpers;
using StuWare.Model;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;

namespace StuWare.Controllers
{
    public class StudentController : StuwareController
    {
        private IStudentRepository _studentRepository;
        private ICityRepository _cityRepository;
        private IDistrictRepository _districtRepository;
        private ILessonRepository _lessonRepository;

        public StudentController(IStudentRepository studentRepository, ICityRepository cityRepository, IDistrictRepository districtRepository, ILessonRepository lessonRepository)
        {
            _studentRepository = studentRepository;
            _cityRepository = cityRepository;
            _districtRepository = districtRepository;
            _lessonRepository = lessonRepository;
        }
        public IActionResult Index()
        {

            return View(_studentRepository.Students);
        }

        [HttpGet]
        public IActionResult Create()
        {

            List<City> cityList = _cityRepository.Cities.ToList<City>();
            ViewBag.ListOfCities = cityList;

            return View();
        }

        [HttpPost]
        public IActionResult Create(Student entity)
        {

            if (ModelState.IsValid)
            {
                _studentRepository.CreateStudent(entity);
                return RedirectToAction("Index");
            }
            else
            {
                List<City> cityList = _cityRepository.Cities.ToList<City>();
                ViewBag.ListOfCities = cityList;
                return View(entity);
              
            }
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            List<City> cityList = _cityRepository.Cities.ToList<City>();
            ViewBag.ListOfCities = cityList;

            return View(_studentRepository.GetById(id));
        }

        [HttpPost]
        public IActionResult Details(Student entity)
        {
            if (ModelState.IsValid )
            {
                _studentRepository.UpdateStudent(entity);
                return RedirectToAction("Index");
            }
            else
            {
                List<City> cityList = _cityRepository.Cities.ToList<City>();
                ViewBag.ListOfCities = cityList;
                return View(entity);
            }
        }

        public IActionResult Delete(int id)
        {
            _studentRepository.DeleteStudent(id);
            return RedirectToAction("Index");
        }


        public JsonResult GetDistricts(int cityId)
        {
            var districtList = _districtRepository.GetByCityId(cityId);
            return Json(new SelectList(districtList, "ID", "Name"));
        }

    }
}

StuWare/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using StuWare.Data.Repository;
using StuWare.Helpers;
using StuWare.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StuWare.Controllers
{
    public class TeacherController : StuwareController
    {

        private ITeacherRepository _teacherrepository;

        public TeacherController(ITeacherRepository teacherrepository)
        {
            _teacherrepository = teacherrepository;
        }

        public IActionResult Index()
        {
            return View(_teacherrepository.Teachers);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Teacher entity)
        {

            if (ModelState.IsValid)
            {
                _teacherrepository.CreateTeacher(entity);
                return RedirectToAction("Index");
            }
            else
            {
                return View(entity);
            }
        }

        public IActionResult Delete(int id)
        {
            _teacherrepository.DeleteTeacher(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            return View(_teacherrepository.GetById(id));
        }

        [HttpPost]
        public IActionResult Details(Teacher entity)
        {
            if (ModelState.IsValid)
            {
                _teacherrepository.UpdateTeacher(entity);
                return RedirectToAction("Index");
            }
            else
            {
                return View(entity);
            }
        }
    }
}

StuWare/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>

    @Html.Partial("_Navbar");
</head>
<body>
    <div class="container">
        <div class="row">
           
                @RenderBody()
           
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>


</body>
</html>

StuWare/Views/Shared/_Navbar.cshtml
@using Microsoft.AspNetCore.Http;
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">

        <a class="navbar-brand" href="#">
            <img src="~/lib/images/logoFontt.PNG" />
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Anasayfa</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Tanımlamalar
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" asp-controller="Student" asp-action="Index">Öğrenci Tanımlamaları</a></li>
                        <li><a class="dropdown-item" asp-controller="Teacher" asp-action="Index">Öğretmen Tanımlamaları</a></li>
                        <li><a class="dropdown-item" asp-controller="Lesson" asp-action="Index">Ders Tanımlamaları</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <div>
            Hoşgeldiniz @Context.Session.GetString("Username") <a asp-action="Logout" asp-controller="User">Çıkış</a>
        </div>
    </div>
</nav>