StuWare/Controllers/LessonController.cs
using Microsoft.AspNetCore.Mvc;
using StuWare.Data.Repository;
using StuWare.Helpers;
using StuWare.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StuWare.Controllers
{
    public class LessonController : StuwareController
    {
        private ILessonRepository _lessonRepository;
        private ITeacherRepository _teacherRepository;

        public LessonController(ILessonRepository lessonrepository, ITeacherRepository teacherRepository)
        {
            _lessonRepository = lessonrepository;
            _teacherRepository = teacherRepository;
        }

        public IActionResult Index()
        {
            return View(_lessonRepository.Lessons);
        }

        [HttpGet]
        public IActionResult Create()
        {

            List<Teacher> teacherList = _teacherRepository.Teachers.ToList<Teacher>();
            ViewBag.ListOfTeachers = teacherList;

            return View();
        }

        [HttpPost]
        public IActionResult Create(Lesson entity)
        {
            if (ModelState.IsValid)
            {
                _lessonRepository.CreateLesson(entity);
                return RedirectToAction("Index");
            }
            else
            {
                List<Teacher> teacherList = _teacherRepository.Teachers.ToList<Teacher>();
                ViewBag.ListOfTeachers = teacherList;
                return View(entity);
            }
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            List<Teacher> teacherList = _teacherRepository.Teachers.ToList<Teacher>();
            ViewBag.ListOfTeachers = teacherList;

            return View(_lessonRepository.GetById(id));
        }

        [HttpPost]
        public IActionResult Details(Lesson entity)
        {

            if (ModelState.IsValid)
            {
                _lessonRepository.UpdateLesson(entity);
                return RedirectToAction("Index");
            }
            else
            {
                return View(entity);
            }

        }


        public IActionResult Delete(int id)
        {
            _lessonRepository.DeleteLesson(id);
            return RedirectToAction("Index");
        }

    }
}

StuWare/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using StuWare.Data.Repository;
using StuWare.Helpers;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;

namespace StuWare.Controllers
{
    public class ReportController : StuwareController
    {
        private IStudentLessonRepository _studentLessonRepository;
        private IStudentRepository _studentRepository;
        private ILessonRepository _lessonRepository;

        public ReportController(IStudentLessonRepository studentLessonRepository, IStudentRepository studentRepository, ILessonRepository lessonRepository)
        {
            _studentLessonRepository = studentLessonRepository;
            _studentRepository = studentRepository;
            _lessonRepository = lessonRepository;
        }

        private static int selectedStudentId = 0;
        public IActionResult Index(int id)
        {
            selectedStudentId = id;
            ViewBag.selectedStudentId = selectedStudentId;

            var studentLessonsList = _studentLessonRepository.StudentLessons.Where(x => x.StudentID.Equals(selectedStudentId));

            double totalGrade = 0, count = 0;
         
            foreach (var item in studentLessonsList)
            {
                if (item.StudentLessonGrade.Count > 0)
                {
                    double avg = item.StudentLessonGrade.Average(x => x.Grade);
                    totalGrade += CalculateGrade(avg);
                    count++;
                }
            }

            ViewBag.Grade = Math.Round((totalGrade / count),2);

            return View(studentLessonsList);
        }

        private double CalculateGrade(double avg)
        {
            double grade = 0;
            if (avg > 85)
            {
                grade = 5;
            }
            else if (avg > 70)
            {
                grade = 4;
            }
            else if (avg > 55)
            {
                grade = 3;
            }
            else if (avg > 45)
            {
                grade = 2;
            }
            else
            {
                grade = 1;
            }
            return grade;
        }
    }
}

StuWare/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using StuWare.Data.Repository;
using StuWare.Helpers;
using StuWare.Model;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;

namespace StuWare.Controllers
{
    public class StudentController : StuwareController
    {
        private IStudentRepository _studentRepository;
        private ICityRepository _cityRepository;
        private IDistrictRepository _districtRepository;
        private ILessonRepository _lessonRepository;

        public StudentController(IStudentRepository studentRepository, ICityRepository cityRepository, IDistrictRepository districtRepository, ILessonRepository lessonRepository)
        {
            _studentRepository = studentRepository;
            _cityRepository = cityRepository;
            _districtRepository = districtRepository;
            _lessonRepository = lessonRepository;
        }
        public IActionResult Index()
        {

            return View(_studentRepository.Students);
        }

        [HttpGet]
        public IActionResult Create()
        {

            List<City> cityList = _cityRepository.Cities.ToList<City>();
            ViewBag.ListOfCities = cityList;

            return View();
        }

        [HttpPost]
        public IActionResult Create(Student entity)
        {

            if (ModelState.IsValid)
            {
                _studentRepository.CreateStudent(entity);
                return RedirectToAction("Index");
            }
            else
            {
                List<City> cityList = _cityRepository.Cities.ToList<City>();
                ViewBag.ListOfCities = cityList;
                return View(entity);
              
            }
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            List<City> cityList = _cityRepository.Cities.ToList<City>();
            ViewBag.ListOfCities = cityList;

            return View(_studentRepository.GetById(id));
        }

        [HttpPost]
        public IActionResult Details(Student entity)
        {
            if (ModelState.IsValid )
            {
                _studentRepository.UpdateStudent(entity);
                return RedirectToAction("Index");
            }
            else
            {
                List<City> cityList = _cityRepository.Cities.ToList<City>();
                ViewBag.ListOfCities = cityList;
                return View(entity);
            }
        }

        public IActionResult Delete(int id)
        {
            _studentRepository.DeleteStudent(id);
            return RedirectToAction("Index");
        }


        public JsonResult GetDistricts(int cityId)
        {
            var districtList = _districtRepository.GetByCityId(cityId);
            return Json(new SelectList(districtList, "ID", "Name"));
        }

    }
}

StuWare/Controllers/StudentLessonController.cs
using Microsoft.AspNetCore.Mvc;
using StuWare.Data.Repository;
using StuWare.Helpers;
using StuWare.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StuWare.Controllers
{
    public class StudentLessonController : StuwareController
    {
        private IStudentLessonRepository _studentLessonRepository;
        private IStudentRepository _studentRepository;
        private ILessonRepository _lessonRepository;

        public StudentLessonController(IStudentLessonRepository studentLessonRepository,IStudentRepository studentRepository,ILessonRepository lessonRepository)
        {
            _studentLessonRepository = studentLessonRepository;
            _studentRepository = studentRepository;
            _lessonRepository = lessonRepository; 
        }

        private static int selectedStudentId = 0;

        public IActionResult Index(int id)
        {
            selectedStudentId = id;
            ViewBag.selectedStudentId = selectedStudentId;

            List<int> selectedClassList = new List<int>();
            var student = _studentRepository.GetById(selectedStudentId);
            var studentlessonsForSpecificYearList = _lessonRepository.Lessons.Where(x => x.Class.Equals(student.ClassYear));

            foreach (var item in studentlessonsForSpecificYearList.ToList())
            {
                if (_studentLessonRepository.StudentLessons.Where(x => x.StudentID.Equals(selectedStudentId) && x.LessonID.Equals(item.ID)).Count() > 0)
                    selectedClassList.Add(item.ID);

            }

            ViewBag.SelectedClassLists = selectedClassList;

            return View(studentlessonsForSpecificYearList);
        }


        public IActionResult Create(int id)
        {
            if (_studentLessonRepository.StudentLessons.Where(x => x.StudentID.Equals(selectedStudentId) && x.LessonID.Equals(id)).Count() > 0)
                throw new Exception("Duplicated");

            _studentLessonRepository.CreateStudentLesson(new StudentLesson
            {
                LessonID = id,
                StudentID = selectedStudentId
            });

            return RedirectToAction("Index", new { id = selectedStudentId });
        }

        public IActionResult Delete(int id)
        {
            int lessonId = id;
            var studentLesson = _studentLessonRepository.StudentLessons.Where(x => x.StudentID.Equals(selectedStudentId) && x.LessonID.Equals(lessonId)).FirstOrDefault();
            _studentLessonRepository.DeleteStudentLesson(studentLesson.ID);
            return RedirectToAction("Index", new { id = selectedStudentId });
        }
    }
}

StuWare/Views/Student/ClassDefinition.cshtml
@model IEnumerable<Lesson>

<table class="table">
    <thead class="table-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">DersAdı</th>
            <th scope="col">Sınıf</th>
            <th scope="col">Ders Ata</th>
            <th scope="col">Sil</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <th scope="row">@item.ID</th>
            <td>@item.Name</td>
            <td>@item.Class</td>

            @if (!(ViewBag.SelectedClassLists as List<int>).Contains(item.ID))
            {
                <td>

                    <a asp-action="ClassDefinitionExec" asp-controller="Student" asp-route-id="@item.ID" asp-route-studentId="@Context.Request.Query["id"]">
                        Dersi Ata
                    </a>
                </td>

            }
            else
            {
                <td>
                    Bu ders atanmıştır.
                </td>
            }
        </tr>
        }
    </tbody>
</table>

<div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <a class="btn btn-primary me-md-2" type="button" asp-action="Create" asp-controller="Lesson">Yeni Ders Ekle</a>
</div>

StuWare/Views/Student/Create.cshtml
@model Student

<div class="container">

    <h2> Create </h2>
    <br />

    <form asp-controller="Student" asp-action="Create" method="post">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="mb-3">

            <label asp-for="Name" class="form-label">Ad</label> <span asp-validation-for="Name" class="text-danger"></span>
            <input asp-for="Name" class="form-control">
        </div>

        <div class="mb-3">
            <label asp-for="LastName" class="form-label">Soyad</label> <span asp-validation-for="LastName" class="text-danger"></span>
            <input asp-for="LastName" class="form-control">
        </div>

        <div class="mb-3">
            <label asp-for="Sex" class="form-label">Cinsiyet</label> <span asp-validation-for="Sex" class="text-danger"></span>
            <select class="form-control">
                <option disabled selected>Cinsiyet Seçin</option>
                <option value="False">Kız</option>
                <option value="True">Erkek</option>
            </select>
        </div>

        <div class="mb-3">
            <label asp-for="LastSchool" class="form-label">Önceki Okul Adı</label> <span asp-validation-for="LastSchool" class="text-danger"></span>
            <input asp-for="LastSchool" class="form-control">
        </div>

        <div class="mb-3">
            <label asp-for="GradeAverage" class="form-label">Not Ortalaması</label> <span asp-validation-for="GradeAverage" class="text-danger"></span>
            <input asp-for="GradeAverage" class="form-control">
        </div>

        <div class="mb-3">
            <label asp-for="ClassYear" class="form-label">Sınıf Yılı</label> <span asp-validation-for="ClassYear" class="text-danger"></span>
            <input asp-for="ClassYear" type="number" class="form-control">
        </div>

        <div class="mb-3">
            <label asp-for="GuardianName" class="form-label">Veli Adı</label> <span asp-validation-for="GuardianName" class="text-danger"></span>
            <input asp-for="GuardianName" class="form-control">
        </div>

        <div class="mb-3">
            <label asp-for="GuardianLastName" class="form-label">Veli Soyadı</label> <span asp-validation-for="GuardianLastName" class="text-danger"></span>
            <input asp-for="GuardianLastName" class="form-control">
        </div>

        <div class="mb-3">
            <label asp-for="GuardianCellPhone" class="form-label">Veli Tel NO.</label> <span asp-validation-for="GuardianCellPhone" class="text-danger"></span>
            <input asp-for="GuardianCellPhone" class="form-control">
        </div>

        <div class="mb-3">
            <label asp-for="GuardianPhone" class="form-label">Veli Ev Tel NO.</label> <span asp-validation-for="GuardianPhone" class="text-danger"></span>
            <input asp-for="GuardianPhone" class="form-control">
        </div>


        <div class="mb-3">
            <label asp-for="GuardianAddress" class="form-label">Veli Adresi</label> <span asp-validation-for="GuardianAddress" class="text-danger"></span>
            <input asp-for="GuardianAddress" class="form-control">
        </div>

        <div class="mb-3">
            <label asp-for="District.City" class="form-label">Şehir</label>
            <select asp-for="District.City.ID" class="form-control" id="CityID" name="CityID" asp-items="@(new SelectList(@ViewBag.ListOfCities,"ID","Name"))">
                <option disabled selected value="">Seçin</option>
            </select>
        </div>

        <div class="mb-3">
            <label asp-for="DistrictID" class="form-label">Bölge</label>
            <select asp-for="DistrictID" class="form-control" id="DistrictID" name="DistrictID">
                <option disabled selected value="">Seçin</option>
            </select>
        </div>


        <button type="submit" class="btn btn-primary">Kaydet</button>
    </form>

</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#CityID').change(function () {
            var url = '@Url.Content("~/")' + 'Student/GetDistricts';
            var ddlSource = "#CityID";
            $.getJSON(url, { CityID: $(ddlSource).val() }, function (data) {
                var items = '';
                $('#DistrictID').empty();
                $.each(data, function (i, district) {
                    items += "<option value='" + district.value + "'>" + district.text + "</option>";
                });
                $('#DistrictID').html(items);
            });
        });
    });
</script>

StuWare/Views/Student/Details.cshtml
@model Student

<div class="container">

    <h2>Öğrenci Detay Ekranı - @Model.Name @Model.LastName</h2>
    <br />

    <form asp-controller="Student" asp-action="Details" method="post">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="mb-3">
            <label asp-for="ID" class="form-label">No</label>
            <input asp-for="ID" readonly="readonly" class="form-control">
        </div>

        <div class="mb-3">
            <label asp-for="Name" class="form-label">Ad</label> <span asp-validation-for="Name" class="text-danger"></span>
            <input asp-for="Name" class="form-control">
        </div>

        <div class="mb-3">
            <label asp-for="LastName" class="form-label">Soyad</label> <span asp-validation-for="LastName" class="text-danger"></span>
            <input asp-for="LastName" class="form-control">
        </div>

        <div class="mb-3">
            <label asp-for="Sex" class="form-label">Cinsiyet</label> <span asp-validation-for="Sex" class="text-danger"></span>
            <select asp-for="Sex" class="form-control">
                <option disabled selected value="">Cinsiyet Seçin</option>
                <option value="False">Kız</option>
                <option value="True">Erkek</option>
            </select>
        </div>

        <div class="mb-3">
            <label asp-for="LastSchool" class="form-label">Önceki Okul Adı</label> <span asp-validation-for="LastSchool" class="text-danger"></span>
            <input asp-for="LastSchool" class="form-control">
        </div>

        <div class="mb-3">
            <label asp-for="GradeAverage" class="form-label">Not Ortalaması</label> <span asp-validation-for="GradeAverage" class="text-danger"></span>
            <input asp-for="GradeAverage" class="form-control">
        </div>

        <div class="mb-3">
            <label asp-for="ClassYear" class="form-label">Sınıf Yılı</label> <span asp-validation-for="ClassYear" class="text-danger"></span>
            <input asp-for="ClassYear" type="number" class="form-control">
        </div>

        <div class="mb-3">
            <label asp-for="GuardianName" class="form-label">Veli Adı</label> <span asp-validation-for="GuardianName" class="text-danger"></span>
            <input asp-for="GuardianName" class="form-control">
        </div>

        <div class="mb-3">
            <label asp-for="GuardianLastName" class="form-label">Veli Soyadı</label> <span asp-validation-for="GuardianLastName" class="text-danger"></span>
            <input asp-for="GuardianLastName" class="form-control">
        </div>

        <div class="mb-3">
            <label asp-for="GuardianCellPhone" class="form-label">Veli Tel NO.</label> <span asp-validation-for="GuardianCellPhone" class="text-danger"></span>
            <input asp-for="GuardianCellPhone" class="form-control">
        </div>

        <div class="mb-3">
            <label asp-for="GuardianPhone" class="form-label">Veli Ev Tel NO.</label> <span asp-validation-for="GuardianPhone" class="text-danger"></span>
            <input asp-for="GuardianPhone" class="form-control">
        </div>

        <div class="mb-3">
            <label asp-for="GuardianAddress" class="form-label">Veli Adresi</label> <span asp-validation-for="GuardianAddress" class="text-danger"></span>
            <input asp-for="GuardianAddress" class="form-control">
        </div>

        <div class="mb-3">
            <label asp-for="District.City" class="form-label">Şehir</label>
            <select asp-for="District.City.ID" class="form-control" id="CityID" name="CityID" asp-items="@(new SelectList(@ViewBag.ListOfCities,"ID","Name"))">
                <option disabled selected value="">Seçin</option>
            </select>
        </div>

        <div class="mb-3">
            <label asp-for="DistrictID" class="form-label">Bölge</label>
            <select asp-for="DistrictID" class="form-control" id="DistrictID" name="DistrictID">
                <option disabled selected value="">Seçin</option>
            </select>
        </div>


        <button type="submit" class="btn btn-primary">Güncelle</button>
    </form>

</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#CityID').change(function () {
            var url = '@Url.Content("~/")' + 'Student/GetDistricts';
            var ddlSource = "#CityID";
            $.getJSON(url, { CityID: $(ddlSource).val() }, function (data) {
                var items = '';
                $('#DistrictID').empty();
                $.each(data, function (i, district) {
                    items += "<option value='" + district.value + "'>" + district.text + "</option>";
                });
                $('#DistrictID').html(items);
            });
        });
    });
</script>

StuWare/Views/Student/Index.cshtml
@model IEnumerable<Student>

    <h2> Öğrenci Listesi </h2>
<table class="table">
    <thead class="table-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Ad</th>
            <th scope="col">Soyad</th>
            <th scope="col">Önceki Okul</th>
            <th scope="col">Veli</th>
            <th scope="col">Veli Tel No.</th>
            <th scope="col">İncele</th>
            <th scope="col">Ders Ata</th>
            <th scope="col">Karne</th>
            <th scope="col">Sil</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <th scope="row">@item.ID</th>
            <td>@item.Name</td>
            <td>@item.LastName</td>
            <td>@item.LastSchool</td>
            <td>@item.GuardianName @item.GuardianLastName</td>
            <td>@item.GuardianCellPhone</td>

            <td>
                <a asp-action="Details" asp-controller="Student" asp-route-id="@item.ID">
                    Güncelle
                </a>
            </td>

            <td>
                <a asp-action="Index" asp-controller="StudentLesson" asp-route-id="@item.ID">
                    Ders Ata
                </a>
            </td>

            <td>
                <a asp-action="Index" asp-controller="Report" asp-route-id="@item.ID">
                    Karne
                </a>
            </td>

            <td>
                <a asp-action="Delete" asp-controller="Student" asp-route-id="@item.ID" onclick="return confirm('Silmek istediğinize emin misiniz?')">
                    Sil
                </a>
            </td>
        </tr>
        }
    </tbody>
</table>


<div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <a class="btn btn-primary me-md-2" type="button" asp-action="Create" asp-controller="Student">Yeni Öğrenci Ekle</a>
</div>